<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE TEXT [
            <!ELEMENT TEXT (HEADER,S+)>
            <!ATTLIST TEXT xml:lang CDATA #IMPLIED>
            <!ELEMENT HEADER (TITLE?,SOUNDFILE?,SPEAKER*)>
            <!ELEMENT TITLE (#PCDATA)>
            <!ATTLIST TITLE xml:lang CDATA #IMPLIED>
            <!ELEMENT SOUNDFILE (#PCDATA)>
            <!ATTLIST SOUNDFILE href CDATA #IMPLIED>
            <!ELEMENT SPEAKER (#PCDATA)>
            <!ATTLIST SPEAKER personId ID #REQUIRED>
            <!ELEMENT S (FORM|TRANSL|AUDIO)*>
            <!ATTLIST S id ID #IMPLIED>
            <!ATTLIST S who IDREF #IMPLIED>
            <!ELEMENT FORM (#PCDATA)>
            <!ATTLIST FORM type CDATA #IMPLIED>
            <!ELEMENT TRANSL (#PCDATA)>
            <!ATTLIST TRANSL xml:lang CDATA #IMPLIED>
            <!ELEMENT AUDIO EMPTY>
            <!ATTLIST AUDIO start CDATA #REQUIRED>
            <!ATTLIST AUDIO end CDATA #REQUIRED>
]>
<TEXT xml:lang="x-sil-TIC">
        <HEADER>
                <TITLE xml:lang="en"> </TITLE>
	</HEADER>
        <S>
                <FORM type="transliteration"> </FORM>
        </S>
</TEXT>
